amazon-ion/ion-schema-kotlin

- src/software/amazon/ionschema/IonSchemaSystem.kt
- src/software/amazon/ionschema/IonSchemaSystemBuilder.kt
- src/software/amazon/ionschema/Type.kt
- src/software/amazon/ionschema/internal/IonSchemaSystemImpl.kt
- src/software/amazon/ionschema/internal/PrivateTrampoline.kt
- src/software/amazon/ionschema/internal/SchemaCore.kt
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- src/software/amazon/ionschema/internal/TypeCore.kt
- src/software/amazon/ionschema/internal/TypeImpl.kt
- src/software/amazon/ionschema/internal/TypeIon.kt
- src/software/amazon/ionschema/internal/constraint/RecurringTypeReference.kt
- src/software/amazon/ionschema/internal/globals.kt
- src/software/amazon/ionschema/internal/util/Range.kt
- src/software/amazon/ionschema/internal/util/RangeIonNumber.kt
- src/software/amazon/ionschema/internal/util/RangeIonPosInt.kt
- test/software/amazon/ionschema/IonSchemaTest.kt
- test/software/amazon/ionschema/internal/util/RangeIonNumberTest.kt
- test/software/amazon/ionschema/internal/util/RangeIonPosIntTest.kt
> Cleanup mostly related to IonSystem usage

- src/software/amazon/ionschema/Authority.kt
- src/software/amazon/ionschema/AuthorityFilesystem.kt
- src/software/amazon/ionschema/internal/IonSchemaSystemImpl.kt
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- src/software/amazon/ionschema/util/CloseableIterator.kt
- test/software/amazon/ionschema/IonSchemaSystemTest.kt
- test/software/amazon/ionschema/internal/util/ValidatorTest.kt
> updates Authority interface to return CloseableIterator<IonValue>

- data/test/constraints/content/struct.isl
- data/test/validation/constraints/content.isl
- src/software/amazon/ionschema/internal/constraint/Fields.kt
> adds support for 'content: closed'

- data/test/constraints/ordered_elements/occurs.isl
- data/test/validation/constraints/ordered_elements.isl
- src/software/amazon/ionschema/internal/constraint/OrderedElements.kt
- src/software/amazon/ionschema/internal/util/Validator.kt
> removes Violations.removeChild(); improves violation details for ordered_elements

- src/software/amazon/ionschema/internal/util/Validator.kt
- test/software/amazon/ionschema/IonSchemaTest.kt
> enables short-circuit logic when isValid() is called

- settings.gradle
- src/software/amazon/ionschema/internal/TypeNullable.kt
- src/software/amazon/ionschema/internal/constraint/TimestampPrecision.kt
- src/software/amazon/ionschema/internal/constraint/TypeReference.kt
- test/software/amazon/ionschema/IonSchemaTest.kt
> addresses various build warnings

- data/test/schema/CommonTypes.isl
- data/test/schema/Customer.isl
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- test/software/amazon/ionschema/IonSchemaImportTest.kt
- test/software/amazon/ionschema/IonSchemaTestSuite.kt
* Changed the parsing of id within import to be a string instead of symbol
* Added new test cases to verify that type imports are happening
* Added new test cases to verify that imported types would be used during validation
> Fix for schema imports with new tests validating

- data/test/constraints/fields/fields.isl
> adds ISL tests for the fields constraint

- src/software/amazon/ionschema/IonSchemaSystem.kt
- src/software/amazon/ionschema/Schema.kt
- src/software/amazon/ionschema/internal/IonSchemaSystemImpl.kt
- src/software/amazon/ionschema/internal/SchemaCore.kt
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- test/software/amazon/ionschema/IonSchemaSystemTest.kt
- test/software/amazon/ionschema/SchemaTest.kt
> adds IonSchemaSystem.newSchema() and Schema.newType() methods

- data/test/constraints/unknown_constraint.isl
> adds test for a type with an unknown constraint (open content ISL)

- data/test/constraints/occurs/fields.isl
- data/test/constraints/occurs/ordered_elements.isl
> adds tests for occurs constraint within ordered_elements

- data/test/schema/deferred_type_resolution.isl
- data/test/schema/invalid.isl
- src/software/amazon/ionschema/internal/ConstraintFactoryDefault.kt
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- src/software/amazon/ionschema/internal/TypeImpl.kt
- src/software/amazon/ionschema/internal/TypeInternal.kt
- src/software/amazon/ionschema/internal/TypeNamed.kt
- src/software/amazon/ionschema/internal/constraint/Element.kt
- src/software/amazon/ionschema/internal/constraint/LogicConstraints.kt
- src/software/amazon/ionschema/internal/constraint/Occurs.kt
- src/software/amazon/ionschema/internal/constraint/Type.kt
- src/software/amazon/ionschema/internal/constraint/TypeReference.kt
> adds support for deferred type resolution while loading a schema

- schema/isl/annotations.isl
- schema/isl/byte_length.isl
- schema/isl/codepoint_length.isl
- schema/isl/container_length.isl
- schema/isl/contains.isl
- schema/isl/content.isl
- schema/isl/non_negative_int.isl
- schema/isl/occurs.isl
- schema/isl/precision.isl
- schema/isl/regex.isl
- schema/isl/scale.isl
- schema/isl/schema.isl
- schema/isl/timestamp_offset.isl
- schema/isl/timestamp_precision.isl
- schema/isl/type.isl
- schema/isl/valid_values.isl
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- src/software/amazon/ionschema/internal/constraint/TypeReference.kt
- test/software/amazon/ionschema/AbstractTestRunner.kt
- test/software/amazon/ionschema/ISLforISLTestRunner.kt
- test/software/amazon/ionschema/IonSchemaTestRunner.kt
> adds ISL for ISL, and a test runner to validate the file-based test ISL

- src/software/amazon/ionschema/internal/SchemaImpl.kt
- test/software/amazon/ionschema/SchemaTest.kt
> adds unit test to assert a proper exception when an unrecognized type reference is encountered

- src/software/amazon/ionschema/Type.kt
- src/software/amazon/ionschema/internal/Constraint.kt
- src/software/amazon/ionschema/internal/ConstraintFactory.kt
- src/software/amazon/ionschema/internal/ConstraintInternal.kt
- src/software/amazon/ionschema/internal/TypeImpl.kt
- src/software/amazon/ionschema/internal/constraint/Fields.kt
- src/software/amazon/ionschema/internal/constraint/TypeReference.kt
Removing the Constraint interface from the public API, as it adds no value there at this time.
> moves Constraint inside the internal package

- src/software/amazon/ionschema/Authority.kt
- src/software/amazon/ionschema/AuthorityFilesystem.kt
- src/software/amazon/ionschema/InvalidSchemaException.kt
- src/software/amazon/ionschema/IonSchemaException.kt
- src/software/amazon/ionschema/IonSchemaSystem.kt
- src/software/amazon/ionschema/IonSchemaSystemBuilder.kt
- src/software/amazon/ionschema/Schema.kt
- src/software/amazon/ionschema/Type.kt
- src/software/amazon/ionschema/Violations.kt
- src/software/amazon/ionschema/module.md
- src/software/amazon/ionschema/util/CloseableIterator.kt
- test/software/amazon/ionschema/AuthorityFilesystemTest.kt
- test/software/amazon/ionschema/IonSchemaSystemTest.kt
- test/software/amazon/ionschema/SchemaTest.kt
- test/software/amazon/ionschema/TypeTest.kt
> adds API and tests against the API for review

- src/software/amazon/ionschema/internal/CommonViolations.kt
- src/software/amazon/ionschema/internal/Constraint.kt
- src/software/amazon/ionschema/internal/ConstraintFactory.kt
- src/software/amazon/ionschema/internal/ConstraintFactoryDefault.kt
- src/software/amazon/ionschema/internal/ConstraintInternal.kt
- src/software/amazon/ionschema/internal/IonSchemaSystemImpl.kt
- src/software/amazon/ionschema/internal/SchemaCore.kt
- src/software/amazon/ionschema/internal/SchemaImpl.kt
- src/software/amazon/ionschema/internal/TypeBuiltinImpl.kt
- src/software/amazon/ionschema/internal/TypeCore.kt
- src/software/amazon/ionschema/internal/TypeImpl.kt
- src/software/amazon/ionschema/internal/TypeInline.kt
- src/software/amazon/ionschema/internal/TypeIon.kt
- src/software/amazon/ionschema/internal/TypeNamed.kt
- src/software/amazon/ionschema/internal/TypeNullable.kt
- src/software/amazon/ionschema/internal/TypeReference.kt
- src/software/amazon/ionschema/internal/util/IonValueExtensions.kt
- src/software/amazon/ionschema/internal/util/StringExtensions.kt
> adds core implementation classes for review

- data/test/constraints/occurs/fields_range_exclusive_nullable.isl
- src/software/amazon/ionschema/internal/constraint/Occurs.kt
> adds fields, occurs, and ordered_elements constraints for review

- src/software/amazon/ionschema/internal/util/Range.kt
- src/software/amazon/ionschema/internal/util/RangeBigDecimal.kt
- src/software/amazon/ionschema/internal/util/RangeBoundaryType.kt
- src/software/amazon/ionschema/internal/util/RangeInt.kt
- src/software/amazon/ionschema/internal/util/RangeIntNonNegative.kt
- src/software/amazon/ionschema/internal/util/RangeIonNumber.kt
- src/software/amazon/ionschema/internal/util/RangeIonTimestamp.kt
- src/software/amazon/ionschema/internal/util/RangeIonTimestampPrecision.kt
> adds range impls and tests for review

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
> adds build files for review

- data/test/constraints/occurs/invalid.isl
- src/software/amazon/ionschema/internal/constraint/Fields.kt
- src/software/amazon/ionschema/internal/constraint/OrderedElements.kt
- test/software/amazon/ionschema/ISLforISLTestRunner.kt
> source improvements related to full source reviews

- data/test/constraints/regex/escape-backspace.isl
- data/test/constraints/regex/escape-tab.isl
- data/test/constraints/regex/multiline.isl
- src/software/amazon/ionschema/internal/constraint/Regex.kt
> adds support for regex multiline; also adds tests for regexes with backspace or tab characters

- data/test/constraints/all_of/inlined_type_import.isl
- data/test/constraints/any_of/inlined_type_import.isl
- data/test/constraints/element/inlined_type_import.isl
- data/test/constraints/fields/inlined_type_import.isl
- data/test/constraints/not/inlined_type_import.isl
- data/test/constraints/one_of/inlined_type_import.isl
- data/test/constraints/ordered_elements/inlined_type_import.isl
- data/test/constraints/type/inlined_type_import.isl
- schema/isl/type.isl
> adds tests to verify support for inlined type imports

- data/test/schema/import/import_inline.isl
- data/test/schema/import/import_inline_a1.isl
- data/test/schema/import/import_inline_a2.isl
- data/test/schema/import/import_inline_a3.isl
> adds test to verify inline type import behavior (and absence of type name conflicts)

- build.gradle
> Move to new sonatype URL

- src/com/amazon/ionschema/Schema.kt
- src/com/amazon/ionschema/Type.kt
- src/com/amazon/ionschema/internal/SchemaCore.kt
- src/com/amazon/ionschema/internal/SchemaImpl.kt
- src/com/amazon/ionschema/internal/TypeCore.kt
- src/com/amazon/ionschema/internal/TypeImpl.kt
- src/com/amazon/ionschema/internal/TypeIon.kt
- src/com/amazon/ionschema/internal/TypeReference.kt
- src/com/amazon/ionschema/internal/util/IonValueExtensions.kt
- test/com/amazon/ionschema/SchemaTest.kt
- test/com/amazon/ionschema/TypeTest.kt
> feat(api): exposes ISL underlying Schema and top-level Type objects

- src/com/amazon/ionschema/IonSchemaSystemBuilder.kt
- src/com/amazon/ionschema/SchemaCache.kt
- src/com/amazon/ionschema/SchemaCacheDefault.kt
- src/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
- test/com/amazon/ionschema/SchemaCacheTest.kt
Resolves #135 
Introduces a new SchemaCache interface and a default implementation.
> feat(cache): enables custom schema caching logic

- src/com/amazon/ionschema/internal/constraint/Regex.kt
Resolves #125 
The result is a simpler implementation, while (hopefully) still blocking features of Java's [Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) class that aren't supported by the [Ion Schema regex constraint](https://amzn.github.io/ion-schema/docs/spec.html#regex).
Also realized having special `when` cases for Ion escapes wasn't necessary, thus removed.
Before merging:  update this PR to reference the latest ion-schema-tests commit after https://github.com/amzn/ion-schema-tests/pull/2 is merged.
> feat(regex): adds support for compound character classes

- README.md
Added kotlin sample to README. Specified schema inline in both code snippets to make things easy.
> Getting started code sample converted to Kotlin & schema specified inline

- src/com/amazon/ionschema/internal/constraint/Annotations.kt
Implements the spec change given in amzn/ion-schema#26
Implements 'closed' annotations. When a schema type has an `annotations` constraint and the list of type annotations is annotated with `closed::`, IonValues will be validated as invalid if they are annotated with anything _not_ in the given list of annotations.
> Implement 'closed' annotations (amzn/ion-schema#26)

- src/com/amazon/ionschema/internal/constraint/TimestampOffset.kt
This is PR adds negation constraint on timestamp offset. 
*Test:*
https://github.com/amzn/ion-schema-tests/pull/10
> added changes for negation constraint on timestamp offset

- src/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
- src/com/amazon/ionschema/internal/constraint/FloatSize.kt
- src/com/amazon/ionschema/internal/util/RangeIonNumber.kt
*Issue https://github.com/amzn/ion-schema/issues/18*
This PR adds changes for `float_size` constraint
*Test*:
https://github.com/amzn/ion-schema-tests/pull/9
> Add changes for `float_size` constraint

- build.gradle
N/A
- Bumps version to 1.2.1-SNAPSHOT
- Though I suspect the next release will not be a patch version, I'd rather just set the snapshot to a new patch version just in case, and change to a minor/major version when the major/minor changes are introduced.
None
> Bumps version to 1.2.1-SNAPSHOT

- build.gradle
N/A
Releases v1.2.1; release notes to be as follows:
> ## What's Changed
> * Fixes git submodule reference to point to the latest commit in ion-schema-tests # 183
> * Updates the dokka gradle plugin to a stable release version # 185
> * Fixes a bug in ResourceAuthority that prevents it from actually loading any resources # 186
>
>
> **Full Changelog**: https://github.com/amzn/ion-schema-kotlin/compare/v1.2.0...v1.2.1
N/A
> Release 1.2.1

- build.gradle
N/A
Bumps version to 1.2.2-SNAPSHOT
N/A
> Bumps version to 1.2.2-SNAPSHOT

- ion-schema/build.gradle
N/A
Increase the version now that 1.3.0 is released.
N/A
> Bumps version to 1.3.1-SNAPSHOT

- ion-schema/build.gradle
N/A
* Increments the minor version for ion-schema-kotlin to v1.4.0
None
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
> Release v1.4.0

- cli/src/main/kotlin/com/amazon/ionschema/cli/Main.kt
- cli/src/main/kotlin/com/amazon/ionschema/cli/commands/ValidateCommand.kt
- ion-schema-cli
- ion-schema/build.gradle
None
* Adds a Validate command to the CLI.
* Fixes the `./ion-schema-cli` wrapper script
None.
> Add `validate` command to CLI

- .github/workflows/main.yml
None
Removes the branch condition on PRs triggering the workflow.
None
> Make workflow run on pull requests

- ion-schema/build.gradle
N/A
Updates the version number for the next release.
N/A
> Release v1.5.0

- ion-schema/build.gradle
N/A
Updates the library version
N/A
> Bumps version to 1.5.1-SNAPSHOT

- ion-schema/build.gradle
N/A
Releasing the "nullability" annotation bugfixes as v1.5.1.
N/A
> Release v1.5.1

- ion-schema/build.gradle
None
Bumps version to the next snapshot version
None
> Bumps version to 1.5.2-SNAPSHOT

- ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
- ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
Followup for amazon-ion/ion-schema#118
* Updates Ion Schema Kotlin so that the footer is optional and so that the footer is the last element of the schema and all trailing values (past the footer) are ignored.
* Updates the `ion-schema-tests` and `ion-schema-schemas` submodules
amazon-ion/ion-schema#118
amazon-ion/ion-schema-tests#50
amazon-ion/ion-schema-schemas#12
> Make schema_footer optional

- ion-schema/build.gradle
> Release v1.6.0

- ion-schema/build.gradle
None
Bumps version to 1.6.1-SNAPSHOT
None
> Bumps version to 1.6.1-SNAPSHOT

- ion-schema/build.gradle
None
Update the version so that we can release #279 
N/A
> Release v1.6.1

- ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Annotations_2_0.kt
None
The current implementation of AnnotationsV2 internally converts the simplified syntax to a type definition (standard syntax) in order to simplify the validation logic. However, it is much faster to directly compare the list of annotations on a value to a set of required and/or permitted annotations, so I updated the AnnotationsV2 model so that it can keep the simplified syntax in a more efficient way.
I created a set of type definitions and some values to test them against (see below). I ran warmups invocations until the time was stable, then I use an "[autorange](https://docs.python.org/3/library/timeit.html#timeit.Timer.autorange)" approach to determine the number of invocations in each sample, and then collected and averaged the ops/s for 30 samples.
Types:
```
{ annotations: …
```
> Improves performance of annotations constraint

- ion-schema/build.gradle
> Release v1.7.0

- ion-schema/build.gradle
> Release v1.8.0
