amazon-ion/ion-schema-kotlin

src/software/amazon/ionschema/Constraint.kt
src/software/amazon/ionschema/Type.kt
src/software/amazon/ionschema/internal/ConstraintFactoryDefault.kt
src/software/amazon/ionschema/internal/ConstraintInternal.kt
src/software/amazon/ionschema/internal/TypeBuiltinImpl.kt
src/software/amazon/ionschema/internal/TypeImpl.kt
src/software/amazon/ionschema/internal/TypeInline.kt
src/software/amazon/ionschema/internal/TypeInternal.kt
src/software/amazon/ionschema/internal/TypeNamed.kt
src/software/amazon/ionschema/internal/TypeNullable.kt
src/software/amazon/ionschema/internal/constraint/Annotations.kt
src/software/amazon/ionschema/internal/constraint/ConstraintBase.kt
src/software/amazon/ionschema/internal/constraint/Element.kt
src/software/amazon/ionschema/internal/constraint/LogicConstraints.kt
src/software/amazon/ionschema/internal/constraint/Occurs.kt
src/software/amazon/ionschema/internal/constraint/TypeReference.kt

- introduces ConstraintInternal interface
- moves Constraint.validate(IonValue, Violations) and TypeInternal.vlaidate(IonValue, Violations) to ConstraintInternal
- changes TypeReference class to factory method
- updates TypeBuiltinImpl to actually implement TypeBuiltin

misc. cleanup

---

data/test/schema/Customer.isl
data/test/schema/import/abcde.isl
data/test/schema/import/import.isl
data/test/schema/import/import_type.isl
data/test/schema/import/import_type_by_alias.isl
data/test/schema/import/invalid.isl
data/test/schema/invalid.isl
data/test/schema/open_content.isl
data/test/schema/util/positive_int.isl
test/software/amazon/ionschema/IonSchemaTestSuite.kt

Resolves #1 
Tests include:
* importing an entire schema
* importing a specific type from a schema
* importing a specific type from a schema using an alias
* verifying that open content in ISL is ignored
* misc. invalid schema tests

adds tests to assert expected schema behavior

---

src/software/amazon/ionschema/Type.kt
src/software/amazon/ionschema/Violations.kt

Resolves #92 
As recommended in #80;  all other public elements already declare their type explicitly.

adds explicit return types for improved readability of public APIs

---

src/software/amazon/ionschema/Schema.kt
src/software/amazon/ionschema/internal/SchemaCore.kt
src/software/amazon/ionschema/internal/SchemaImpl.kt
test/software/amazon/ionschema/SchemaTest.kt

Resolves #73 
Following the pattern of PCollection's `PMap.plus` and Kotlin's `Map.plus`, adds `Schema.plusType()` methods while maintaining Schema immutability.

adds fun Schema.plusType(String | IonStruct): Schema

---

data/test/constraints/not/empty_type.isl
test/software/amazon/ionschema/IonSchemaTestRunner.kt

Resolves #71 
Test had been moved to data/test/constraints/not/empty_type.isl
Test required the default "type: any" behavior to be overridden in order to verify that "not: {}" (aka "not: { type: any }") is valid for null values.  That's why it was failing prior to this change.

fixes 'not: {}' test and removes it from the blacklist

---

build.gradle
src/software/amazon/ionschema/internal/util/RangeIonTimestampPrecision.kt

ion-java 1.4.0 introduced a new `Timestamp.Precision` which breaks a `when` clause in `IonTimestampPrecision` 

upgrades to s.a.i.ion-java:1.4.0

---

data/test/constraints/occurs/validation_ordered_elements.isl
data/test/constraints/occurs/validation_ordered_elements_optional.isl
data/test/constraints/ordered_elements/occurs_3.isl
data/test/constraints/ordered_elements/validation_core_types.isl
data/test/constraints/ordered_elements/validation_inlined_types.isl
src/software/amazon/ionschema/internal/constraint/Annotations.kt
src/software/amazon/ionschema/internal/constraint/OrderedElements.kt
src/software/amazon/ionschema/internal/constraint/StateMachine.kt
src/software/amazon/ionschema/internal/util/IntRange.kt

via an enhanced StateMachine implementation;  updates the annotations constraint accordingly
Addresses the ordered_elements backtracking TBD called out pull request #84.  Resolves #75 
Note that some validation details have been dropped as it's not clear how to represent such details when the state machine has followed multiple, parallel paths.

updates the ordered_elements constraint to follow multiple solution paths

---

build.gradle

Koltin javadoc is generated by the dokka task and not the javadoc taks
so the javadocJar task that generates the javadoc artifact has to depend
on dokka
Tested with `./gradlew publishToMavenLocal` and inspecting the generated javadoc jar

fixes javadocJar task

---

data/test/schema/import/import_schema_with_aliased_type.isl
data/test/schema/import/import_schema_with_aliased_type_invalid.isl
src/com/amazon/ionschema/internal/SchemaImpl.kt
src/com/amazon/ionschema/internal/TypeAliased.kt
test/com/amazon/ionschema/ISLforISLTestRunner.kt

Resolves #115 
The import_schema_with_aliased_type_invalid.isl test is added to ISLforISLTestRunner's skip list because that test runner can only recognize invalid ISL -- it can't recognize that the `positive_int` type should not be available (which is why IonSchemaTestRunner recognizes it as invalid when the schema is loaded).

adds propagation of type aliases when importing a schema (#115)

---

src/com/amazon/ionschema/internal/constraint/Occurs.kt

This cloned value doesn't seem to be used anywhere, and can be expensive
to compute.
For my test document, this reduced the time to validate from ~15 seconds
to around ~2 seconds.

Improve performance of Occurs constraint

---

src/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
test/com/amazon/ionschema/IonSchemaSystemTest.kt

Resolves #129 by changing `return` to `return@getOrPut` so the cache actually gets populated.

fix(cache): now actually caches Schema objects

---

src/com/amazon/ionschema/AuthorityFilesystem.kt
test/com/amazon/ionschema/AuthorityFilesystemTest.kt

Resolves #132 
* throws `FileNotFoundException` if requested to resolve a schema id outside the `basePath`
* also changed the exception to throw the more appropriate `FileNotFoundException` (instead of `IllegalArgumentException`)

fix(authorityfs): restricts file access to be within the specified basePath only

---

src/com/amazon/ionschema/IonSchemaSystemBuilder.kt
src/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
src/com/amazon/ionschema/internal/SchemaImpl.kt
test/com/amazon/ionschema/ISLforISLTestRunner.kt
test/com/amazon/ionschema/SchemaTest.kt

* requires all top-level type definitions to have a name (otherwise there's no good way to refer to them)
* I mistakenly pushed https://github.com/amzn/ion-schema-tests/commit/9937507ee8f11949e6f0489bee6f54b83c3f157f without a review; please comment on that as well
* the majority of test files in ion-schema-tests contain type definitions that don't have a name. these proposed changes include logic in ISLforISLTestRunner.kt to provide a type name, if absent; this allows all the ion-schema-tests test cases to pass without needing to provide a name for each type
* for backwards compatibility, if needed, provides an option to not throw on types that don't have a name
Resolves #139 
By submitting this pull request, I confirm that my contribution is made under the …

fix(validation): requires all top-level type definitions to have a name

---

src/com/amazon/ionschema/Import.kt
src/com/amazon/ionschema/Schema.kt
src/com/amazon/ionschema/internal/ImportImpl.kt
src/com/amazon/ionschema/internal/SchemaCore.kt
src/com/amazon/ionschema/internal/SchemaImpl.kt
test/com/amazon/ionschema/SchemaImportTest.kt
test/com/amazon/ionschema/SchemaTest.kt

Resolves #137 
#143 enabled callers to retrieve the ISL underlying Schema and Type objects.  This PR enables callers to retrieve schemas and types *imported* by a schema (and thereby gain access to the underlying ISL of those objects).
Prior to merging:  update the ion-schema-tests submodule after merging https://github.com/amzn/ion-schema-tests/pull/3.

feat(api): adds API for retrieving the types imported by a schema

---

src/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
src/com/amazon/ionschema/internal/SchemaImpl.kt
src/com/amazon/ionschema/internal/TypeCore.kt
src/com/amazon/ionschema/internal/TypeImpl.kt
src/com/amazon/ionschema/internal/TypeInternal.kt
src/com/amazon/ionschema/internal/TypeIon.kt
src/com/amazon/ionschema/internal/TypeReference.kt
test/com/amazon/ionschema/IonSchemaTestRunner.kt

*Issue #, if available:* https://github.com/amzn/ion-schema-kotlin/issues/117
Adds graceful handling of redundant imports by checking the schemaId of a type. If two types have the same name and the same schemaId, it is considered a redundant important and is ignored.

adds graceful handling of redundant imports

---

build.gradle

I noticed that the Travis build failed on PR #151 , which only changed the README. This indicates that something external changed in Travis, which began complaining about the Kotlin version. Maybe this will fix it.

Bumps kotlin version in build.gradle to 1.3.72

---

src/com/amazon/ionschema/internal/SchemaImpl.kt
test/com/amazon/ionschema/SchemaImportTest.kt

*Issue #153*
This PR works on loading schema with symbol or string as ID according to the [spec](https://amzn.github.io/ion-schema/docs/spec.html#grammar). 
*Task:*
1. Inside `loadHeader` method, store ID as `IonSymbol` or `IonString` based on the input. 
*Test:*
getImport_new_schema_from_symbol:  added a unit test for verification.

Schema import id normalize

---

test/com/amazon/ionschema/IonSchemaTestRunner.kt

In order to solve the cyclic dependency issue (specified by [this PR](https://github.com/amzn/ion-schema-kotlin/pull/157)), we have to change the way the schemaId is passed in the testSuite.
**Changes:**
1. Instead of using the `testName` stating file path without  '.isl', will be using `testName` with the '.isl' inside `IonSchemaTestRunner`. 
2. This will allow the cyclic dependency check to have a unique Id pattern followed, which can help in defining equality of import ids.

Updated testSuite to pass filename as id instead of testName

---

src/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
src/com/amazon/ionschema/internal/constraint/Utf8ByteLength.kt

This PR adds a new constraint `utf8_byte_length` for the number of bytes to allow a particular value or range of values in the UTF8 representation of a string.
*Test:*
https://github.com/amzn/ion-schema-tests/pull/7
*Schema:*
https://github.com/amzn/ion-schema-schemas/pull/3
*Schema Documentation:*
https://github.com/amzn/ion-schema/pull/32

adding changes for utf8_byte_length constraint

---

test/com/amazon/ionschema/AbstractTestRunner.kt
test/com/amazon/ionschema/IonSchemaTestRunner.kt

N/A
Given a [schema definition test](https://github.com/amzn/ion-schema-tests#user-content-schema-definition-test) like this:
```
schema_header::{}
type::{
name: Foo,
type: struct,
fields: {
a: int,
b: string,
}
}
schema_footer::{}
valid::{
Foo: [
{ a: 1, b: "hello" },
{ a: 2, b: "world", c: "open content" },
],
}
invalid::{
Foo: [
{ a: "should be int", b: "a string" },
{ a: 1, b: a_symbol },
],
}
```
The `IonSchemaTestRunner` would discover the schema header, and pass the sequence of ion values to the `SchemaImpl` constructor. Because ISL itself allows open content, the `SchemaImpl` would consume _all_ the ion values from the test file—including the `valid::` and `invalid::` test cases. Then the test runner tries to run the test …

Fixes a bug in IonSchemaTestRunner that caused it to silently ignore some test cases

---

src/com/amazon/ionschema/internal/SchemaImpl.kt
test/com/amazon/ionschema/ISLforISLTestRunner.kt

_Description of changes:_
Fixes a bug that allowed you to define two types with the same name in a single schema ([example of what should not be allowed](https://github.com/amzn/ion-schema-tests/pull/12/files#diff-f1583845208143a2c16e9f91fe8141073f6985e3f6c75367b8f2b25fafd9e1b4)). When there are two types with the same name _in the same schema_, the current behavior is that one will silently overwrite the other.
This change does not protect against the case where the type is an exact copy. Eg.
```
schema_header::{
// ...
}
type::{ name: foo, type: int }
type::{ name: foo, type: int }
schema_footer::{}
```
However, this example (even though it is not supposed to be allowed) is not going to lead to any undefined or unexpected behavior.
_Tests:_ amzn/ion-schema-tests#12
_Schema:_ N/A
_Schema …

Fixes a bug that allowed conflicting type definitions in a single schema

---

build.gradle
src/com/amazon/ionschema/ResourceAuthority.kt
test/com/amazon/ionschema/ResourceAuthorityTest.kt

Fixes #156 
Copies the `ion-schema-schemas` definition of ISL into the `ion-schema-kotlin` build output (as a resource in the jar) so that users of `ion-schema-kotlin` don't need to pull in any other dependency to get the ISL for ISL.
Also adds an Authority for accessing the schemas. The `ResourceAuthority` can load schemas that are bundled as a resource in a jar, and it comes with a static factory method for accessing the ISL for ISL schemas.
N/A
Note that this goes against the decision in #122 . The rationale for ignoring that precedent now is:
1. The extra size is trivial—the total size of the `ion-schema-kotlin` jar is approximately 266kb (~500kb uncompressed), …

Adds ion-schema-schemas to the ion-schema-kotlin jar and provides an Authority for accessing them

---

test/com/amazon/ionschema/AbstractTestRunner.kt

N/A
Adds more detail to the test names in AbstractTestRunner so that when iterating the ion-schema-tests files, the test "class" name will include the subclass of AbstractTestRunner and the name of the test case file.
The purpose of this is to make it easier to read the test results.
Eg. prior to this change, we would get a test report with two different tests named `constraints/all_of/core_types`, now we get `ISLforISLTestRunner: constraints/all_of/core_types` and `IonSchemaTestRunner: constraints/all_of/core_types`
N/A

Update test names in AbstractTestRunner

---

build.gradle

N/A
This is an updated fix for https://github.com/amzn/ion-schema-kotlin/issues/130 now that Dokka is stable. It will eliminate the manual steps for generating correct Javadoc in our release process.
I tested this manually when I was publishing the 1.2.0 release, so I can confirm that it works.
N/A

Updates the dokka gradle plugin to a stable release version

---

src/com/amazon/ionschema/ResourceAuthority.kt
test/com/amazon/ionschema/ResourceAuthorityTest.kt

N/A
There is a logic error in the `ResourceAuthority`. When a new instance is initialized, it normalizes the root path to always end with `/`, but when it loads a resources, it always adds another `/` on the end of the root path. This change makes `ResourceAuthority` use the JDK's file related APIs to correctly concatenate the parts of the resource path and then normalize the result. 
This logic error was not detected in unit tests because `foo//bar` and `foo/bar` are considered equivalent paths on *nix file systems, but they are not equivalent paths inside of a zip file (or in our case, a jar). The gradle junit task uses the compiled `.class` files and finds resources in the local file system for running tests rather than having the …

Fixes a bug in ResourceAuthority that prevents it from actually loading any resources

---

src/com/amazon/ionschema/internal/SchemaImpl.kt
test/com/amazon/ionschema/SchemaTest.kt

#95 
Throws an `InvalidSchemaException` if the schema contains an ISL version marker for a version other than 1.0.
This is _technically_ a breaking change, but it should not be a _substantive_ breaking change since there are no other ISL versions in existence, and no one should be adding ISL version markers other than `$ion_schema_1_0`.
Why are we making this change? Because otherwise, users could start creating schemas with (for example) `$ion_schema_2_0`, and whenever support for `$ion_schema_2_0` is released, there could be unexpected behavior changes for the user's schema.
Also, [according to the spec](https://amzn.github.io/ion-schema/docs/spec.html#schema-definitions), schemas are required to start specifically with …

Adds check to make sure ISL version marker is valid

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/NFA.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/OrderedElements.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/OrderedElementsNfaStatesBuilder.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IntRange.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/constraint/NFATest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/constraint/OrderedElementsTest.kt

https://github.com/amzn/ion-schema/issues/62
Fixes the incorrect behavior described in https://github.com/amzn/ion-schema/issues/62. Also updates the `ion-schema-tests` submodule to the latest commit.
https://github.com/amzn/ion-schema-tests/pull/18

Fix implementation of `ordered_elements`

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeIonTimestampPrecision.kt

Fixes #193 
Changes `RangeIonTimestampPrecision` so that calling `valueOf()` for the `IonTimestampPrecision` happens after the check for `min` and `max`. Also now it passes the symbols `min` and `max` to the range delegate instead of converting them to `Int.MIN_VALUE` and `Int.MAX_VALUE`.
Updates the `ion-schema-tests` submodule to have the test cases from https://github.com/amzn/ion-schema-tests/pull/19.
https://github.com/amzn/ion-schema-tests/pull/19
**_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._**

Fix timestamp precision ranges to allow 'min' and 'max'

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/CodepointLength.kt

Fixes #190 
Changes validation to use `String.codePointCount` instead of `String.length`.
Updates the `ion-schema-tests` submodule to have the test cases from https://github.com/amzn/ion-schema-tests/pull/20.
https://github.com/amzn/ion-schema-tests/pull/20
**_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._**

Fixes codepoint_length incorrectly counting multi-unit codepoints

---

.github/workflows/main.yml
README.md
build.gradle

N/A
When working on a recent bugfix, I realized that we didn't have any code coverage analysis as part of the gradle build. So, this change adds the `jacoco` gradle plugin. It also updates the `main.yml` github workflow to generate the coverage reports and upload them to codecov. (I took the liberty of setting up the codecov app for `ion-schema-kotlin` already.)
...and while I was working on that github workflow, I took the opportunity to do a little housecleaning. I removed the non-LTS versions of java from the build matrix, switched to the Corretto JDK distribution, updated some of the github actions to the latest version of the action, and changed the triggers of the workflow so that it will try to build changes regardless of the …

Adds code coverage report

---

ion-schema/build.gradle

N/A
There have been a few bugfixes. This bumps to a new minor version in preparation of a new release. It also updates the developer organization URL in the publish plugin to point to the `amazon-ion` GitHub organiation.
N/A

Prepare v1.3.0 release

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/LogicConstraints.kt

Fixes #200
Returns without adding a violation/issue as soon as the first match is discovered.
N/A
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*

Adds early-exit logic to `any_of` implementation

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/ValidValues.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IntRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Range.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeBigDecimal.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeInt.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeIonNumber.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeIonTimestamp.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeIonTimestampPrecision.kt

No issue, but this fixes the bug described in https://github.com/amzn/ion-schema-tests/pull/22
* Updates `ion-schema-kotlin` to have the latest changes in `ion-schema-tests` (see related PRs below)
* Adds the `operator` keyword to the `contains` functions for all `Range` implementations. This is not strictly necessary, but it makes the changes in `valid_values` implementation a little more concise, and I added it to all of the other `Range`s for consistency.
* Fixes `valid_values` implementation so that it doesn't fail fast (regardless of other possible values) when a timestamp with unknown offset is compared with a range. …

Fixes incorrect fast-fail evaluation of timestamps with unknown offset

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Annotations.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/ValidValues.kt

N/A
* Updates `annotations` implementation to reject `document`s
* Adds a note to `valid_values`
* Updates to the latest commit in the `ion-schema-tests` submodule
https://github.com/amzn/ion-schema/pull/73
https://github.com/amzn/ion-schema-tests/pull/24

Updates annotations and valid_values constraints w.r.t. documents

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/ValidValues.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeIonTimestamp.kt

Fixes #204
Fixes `RangeIonTimestamp` and `ValidValues` to not automatically reject timestamps with unknown offsets.
https://github.com/amzn/ion-schema-tests/pull/25

Fixes timestamp ranges incorrectly rejecting timestamps with unknown offsets

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeInternal.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeOrNullDecorator.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeReference.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Annotations_1_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Contains.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/TimestampOffset.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/ValidValues.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonSchema_2_0_Util.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Preconditions.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Range.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/RangeIonTimestamp.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/util/PreconditionsTest.kt

#207 
* Adds `SchemaImpl_2_0`. Rather than add a lot of branching into a single `Schema` implementation, I figured it would be more readable and easier to not make a mistake by having two separate implementations. I will not be duplicating everything—only things where there is substantially different logic to write. For now, the difference is that `SchemaImpl_2_0` has much stricter validations that `SchemaImpl_1_0` and it has no branches to support transitive imports. There still needs to be further work to support the `user_content` field in the schema header, and how transitive imports will (not) work with Ion Schema 1.0 schemas that use transitive imports.
* Renames `Annotations.kt` to `Annotations_1_0.kt`. This constraint is the only …

Adds SchemaImpl_2_0 with support for a subset of constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Exponent.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207
* Adds the `exponent` constraint
* Adds exponent tests cases to `IonSchemaTests_2_0` suite
* `exponent` test cases https://github.com/amzn/ion-schema-tests/pull/29

Adds support for Ion Schema 2.0 exponent constraint

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Regex.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207 
* Adds changes for regex constraint in Ion Schema 2.0—specifically, supporting character class meta-chars inside a user character class.
* Also fixes a bug where the Regex validator was not checking for a range quantifier with no lower bound, which would result in a `PatternSyntaxException` instead of an `InvalidSchemaException`
* Adds `regex` tests to the `IonSchemaTests_2_0` suite
* Updates `regex` in the constraint Factory to support ISL 2.0
Regex tests: https://github.com/amzn/ion-schema-tests/pull/31

Adds support for Ion Schema 2.0 regex constraint

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/FieldNames.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207
* Adds the `field_names` constraint
* Updates `IonSchemaTests_2_0` to include the `field_names` test cases
* test cases https://github.com/amzn/ion-schema-tests/pull/30
* spec https://amzn.github.io/ion-schema/docs/isl-2-0/spec#field_names

Adds support for Ion Schema 2.0 field_names constraint

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Fields.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207
* Adds support for Ion Schema 2.0 changes for `fields`—specifically, if version is ISL 2.0, check for the `closed::` annotation instead of `content: closed`, validate that no extra/illegal annotations are present.
* Duplicate field definitions have undefined behavior in Ion Schema 1.0 (spec and implementation) and they are explicitly prohibited in Ion Schema 2.0, so I went ahead and made the duplicate fields definition check apply to both versions. I think it's better to throw an exception than it is to leave the undefined behavior as is.
* Adds `fields` test cases to `IonSchemaTests_2_0` suite
* test cases https://github.com/amzn/ion-schema-tests/pull/30
_By …

Adds support for Ion Schema 2.0 fields constraint

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Ieee754Float.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207 
* Adds the `ieee754_float` constraint
* Updates the `IonSchemaTests_2_0` suite to include the `ieee754_float` test cases
Test cases: https://github.com/amzn/ion-schema-tests/pull/29

Adds support for Ion Schema 2.0 ieee754_float constraint

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Annotations_2_0.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207 
* Adds an implementation of the `annotations` constraint for Ion Schema 2.0
* Updates the `IonSchemaTests_2_0` suite to include the `annotations` test cases
* Test cases created in https://github.com/amzn/ion-schema-tests/pull/30

Adds support for Ion Schema 2.0 annotations constraint

---

ion-schema/src/main/kotlin/com/amazon/ionschema/IonSchemaSystemBuilder.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonSchema_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonSchema_2_0_Util.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonValueExtensions.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Preconditions.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

#207 
* Adds support/validation for all aspects of open content in Ion Schema 2.0.
Test cases:
https://github.com/amzn/ion-schema-tests/issues/39

Adds support and validations for open content in Ion Schema 2.0

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeReference.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonSchema_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Preconditions.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/util/PreconditionsTest.kt

#207 
* Adds support for Ion Schema 2.0 imports
* Updates ion-schema-tests submodule to latest commit
* Adds several more validation helper functions to clean up the validations in `SchemaImpl_2_0`
Note that the CodeCov/patch report is failing because Jacoco doesn't understand how to measure code coverage for `inline` functions. (I've created https://github.com/amzn/ion-schema-kotlin/issues/221 to track fixing our code coverage reports.)
Tests were added in https://github.com/amzn/ion-schema-tests/pull/43

Adds Ion Schema 2.0 support for imports

---

cli/src/main/kotlin/com/amazon/ionschema/cli/commands/ValidateCommand.kt
ion-schema-cli

None
* Adds support for reading from `stdin` in a [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) or piped from another command
* Adds machine-parseable output
* `type` is now an argument rather than an option (since it is/was always mandatory anyway)
* Adds option to slurp the input lines as a single input
* Adds option to suppress the output messages
* Adds option to have non-zero exit code when a value is invalid
* Refactors authority configuration so that you can have multiple authorities
* Makes ISL 2.0 the default version if not specified
* Adds a lot more examples and other info to `ion-schema-cli validate --help`
New `--help` output:
```
❯ ./ion-schema-cli validate --help
Usage: ion-schema-cli …
```

Adds support for reading from stdin

---

cli/src/main/kotlin/com/amazon/ionschema/cli/commands/ValidateCommand.kt

None.
The `ion-schema-cli validate` command behavior does not match the behavior described in `--help`—default Ion Schema version was 1.0 instead of 2.0. This PR fixes it by making it use ISl 2.0 by default.
None.

Fix default version of Ion Schema used by `ion-schema-cli validate`

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeCore.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/NFA.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/OrderedElements.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/OrderedElementsNfaStatesBuilder.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonValueExtensions.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/constraint/NFATest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/constraint/OrderedElementsTest.kt

Fixes #110 
This adds better messages for the ordered elements constraint. It's impossible to fully determine what the "cause" of the validation failure is because that requires a better understanding of the data than what is in scope for Ion Schema, and it seems like it also requires some amount of "intuition".
For example, if you expect letters in alphabetical order, then `(a b d c)` is invalid. The _fact_ that it is invalid will be detected at the letter 'c', but it's not really decidable whether the problem is the 'c' or the 'd' that precedes it.
The strategy I've chosen for the violation messages is to report all violations for the first element that does not match any possible "branches" in the NFA.  See `OrderedElementsTest.kt` …

Adds useful violation messages for ordered_elements

---

ion-schema/build.gradle
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/DeferredReference.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/DeferredReferenceManager.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaContent.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaContentCache.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/DeferredReferenceManagerTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/DeferredReferenceTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/SchemaContentCacheTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/SchemaContentTest.kt

Partial progress for fixing #209 
* The current implementation does a depth first traversal, recursively loading schemas until it either hits a leaf node, or it discovers a cycle. It also eagerly loads all imported types, and so the types in Schema A cannot be resolved until all of its imports are loaded. When there's a cycle, we end up with a chicken and egg problem. Schema A cannot load its types until its imports from Schema B are loaded, and Schema B cannot load its types until its imports from Schema A are loaded.
* New implementation
* A schema is loaded in two phases.
* The first phase simply loads the Ion stream into a `SchemaContent` object. This is enough for us to inspect the names of the types declared by the schema, and as a result we can be sure that a type _exist_ in a …

Adds DeferredReferenceManager and SchemaContentCache

---

ion-schema/src/main/kotlin/com/amazon/ionschema/IonSchemaVersion.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaContent.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_1_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaVersionTest.kt

None.
I discovered more inconsistencies with version marker detection, so we're revisiting this... again.
* Adds isVersionMarker(IonValue) to IonSchemaVersion and corresponding unit tests
* Replaces conditional checks in other part of the code with the new function
None.

Consolidates version marker detection logic in IonSchemaVersion

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactory.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaCore.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_1_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeBuiltinImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeInline.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeReference.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Annotations_2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Element.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/FieldNames.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Fields.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/LogicConstraints.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Occurs.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/OrderedElements.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Type.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaSystemTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/constraint/OrderedElementsTest.kt

Continuation of #209 
See #234 for overall strategy.
* This passes the `DeferredReferenceManager` through all of the existing code, but does not actually use it yet for creating type references.
* Most of the code changes are just function signatures getting an extra parameter for the `DeferredReferenceManager`.
* `IonSchemaSystemImpl` has new functions to help mediate between the caches and use the reference manager.
None.

Wires the DeferredReferenceManager through all of the existing code

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ImportImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_1_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0_Test.kt

Continuation of fixing #209 
For overall strategy, see #234 
* `SchemaImpl_2_0` gets a considerable rewrite of how imports are handled so that imported schemas can be lazily loaded. It uses the DeferredReferenceManager to create all imported type references. Also treats the core types as if they are imported (which they are) which cuts down on extra code branching.
* `ImportImpl` now resolves the schema lazily, so that we can load schemas in a loop rather than recursively. (This is what required the one-line change in `SchemaImpl_1_0`.)
* Adds `SchemaImpl_2_0_Test`
* Adds an `internal` function to get the core types for any supported ISL version to `IonSchemaSystemImpl`
* Updates `IonSchemaTestsRunner` so that it now runs the header …

Fixes cyclical import resolution for SchemaImpl_2_0 header imports

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_1_0.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/SchemaTest.kt

Continuation of #209 
For overall strategy, see #234
This is the the equivalent to #238, but this is for `SchemaImpl_1_0`.
* Gets rid of schemaImportSet in IonSchemaSystemImpl in favor of just catching a StackOverflowException.
* Updates import logic in SchemaImpl_1_0 to use new DeferredReferences, and fallback to the old logic if transitive imports are enabled.
* Updates IonSchemaTestsRunner to skip the imports/cycle tests when running tests with transitive import enabled
* Updates `ion-schema-tests` submodule to the latest commit
* Skips an unrelated failing test for ISL 2.0.
See changed files for changes in ion-schema-tests.
By submitting this pull request, I confirm …

Fixes cyclical import resolution for SchemaImpl_1_0 header imports

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/DeferredReference.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaContentCache.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeNullable.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeReference.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Fields.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Occurs.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonValueExtensions.kt

Fixes #246 
Basically, when constructing a `TypeNullable`, in the `init` block, it tries to check the Ion type of the type that it is decorating. If it determines that the Ion type is `IonType.DATAGRAM`, it throws an exception because there is no such thing as a null datagram. There is no nice way to fix this, so this errs on the side of being overly permissive—if we run into an unresolved type reference, the `TypeNullable` initializer swallows the exception and just moves on.
While I was working on this, I also discovered that `ion-schema-kotlin` is incorrectly allowing `nullable::` and `$null_or::` annotations on variably occurring type definitions (i.e. types with `occurs` in them), so I fixed that as well as refactoring `Occurs` …

Fix multiple bugs related to nullability annotations

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Regex.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/regex.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/Constraint.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ContinuousRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/DiscreteIntRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ExperimentalIonSchemaModel.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/HeaderImport.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/Ieee754InterchangeFormat.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/NamedTypeDefinition.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/SchemaDocument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TimestampOffsetValue.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TimestampPrecisionValue.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TypeArgument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TypeDefinition.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/UserReservedFields.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ValidValue.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/VariablyOccurringTypeArgument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/aliases.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/ContinuousRangeTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/DiscreteRangeTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/Ieee754InterchangeFormatTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/SchemaDocumentTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/TimestampOffsetValueTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/TimestampPrecisionValueTest.kt

#250 
Also, partial work on #109 in that this PR has new range implementations that will eventually replace the existing range implementations.
Adds a model for Ion Schema. Currently the model is opt-in only—gated by the `@ExperimentalIonSchemaModel` annotation—and subject to breaking changes.
A few questions/comments for reviewers:
* I have decided to use the term "Type Argument" instead of "type reference" to refer to the thing that you provide to a constraint (such as `element`, `all_of`, etc.). This is a departure from the spec, but I believe it will eliminate the confusion between a "reference" and a so-called "type reference" (that could be a "reference", an inline import, or an inline type). I plan to update the spec to use the new …

Adds ISL model

---

ion-schema/src/main/kotlin/com/amazon/ionschema/InvalidSchemaException.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonTreePath.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ReadError.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ReaderContext.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ConstraintReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/util.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/IonSchemaResult.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/ReaderContextTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/util/IonTreePathTest.kt

Adds interfaces and common utilities for implementing an `IonSchemaReader` that will read Ion into the new ISL model. One improvement in particular over the existing reader logic *aside from the fact that this operates on the new model) is that this is designed to report multiple errors in a single schema document instead of just throwing an exception at the first error.
None

Adds the framework pieces for an Ion Schema reader that uses the ISL model

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/Constraint.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ContinuousRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/DiscreteIntRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/SchemaDocument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TypeArgument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TypeDefinition.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/UserReservedFields.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ValidValue.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/aliases.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/util.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/Bag.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/bags.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/SchemaDocumentTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/util/BagTest.kt

None
As I was working on the reader implementation, I ran into some issues with the model that required some changes.
Here's what's included:
- Several classes are changed to `data` classes so that we get an automatically created implementation of `equals` and `hashcode`.
- In `TypeDefinition`, the `constraints` are changed from a `List` to a `Set`. This is because the order does not matter for equality, and if two constraints are equal they are redundant, so we don't need to have both instances of the same thing in the set.
- Adds a `Bag` (aka Multiset) data type
- In `TypeDefinition`, the `openContent` is changed from a `List` to a `Bag`. Again, the order does not matter for equality, but we cannot use a`Set` in this case because …

Updates the model

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Preconditions.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ConstraintReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/FieldNamesReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/Ieee754FloatReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/RegexReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/util.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/FieldNamesReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/Ieee745FloatReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/RegexReaderTest.kt

#256
* Updates the `ConstraintReader` interface to better suit the mediator pattern.
* Adds readers for `field_names`, `ieee754_float`, and `regex`
None.

Adds readers for field_names, ieee754_float, and regex

---

ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt

#256 
Adds initial, partial implementation of `TypeReaderV2_0` and `IonSchemaReaderV2_0`, but more importantly, it sets up a test runner that can leverage `ion-schema-tests` for the reader implementation.
None.

Adds impl of IonSchemaReaderV2_0 and ion-schema-tests for readers

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/Preconditions.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ExponentReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/LengthConstraintsReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/PrecisionReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ExponentReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/LengthConstraintsReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/PrecisionReaderTest.kt

#256 
* Adds readers for all of the ISL 2.0 constraints that take an int range—`byte_length`, `codepoint_length`, `container_length`, `exponent`, `precision`, and `utf8_byte_length`
None

Adds readers for exponent, precision, and __length constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ElementV2Reader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/LogicConstraintsReader.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ElementV2ReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/LogicConstraintsReaderTest.kt

#256 
Implements `readTypeArg()` and adds readers for some constraints that depend on type arguments (`element` and the "logic" constraints). Updates `ReaderTests` to cover all of the constraints readers that were added and the `$null_or` test cases.

Adds readers for element and logic constraints

---

build.gradle
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/FieldsV2Reader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/OrderedElementsReader.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/FieldsV2ReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/OrderedElementsReaderTest.kt

#256 
Commit: "Adds readers..."
* Adds real implementation of `TypeReaderV2_0.readVariablyOccurringTypeArg()`
* Adds ConstraintReader implementations for `fields` and `ordered_elements`
Commit: "Adds implementation of readNamedType"
* Adds implementation of `readNamedType`. Updates tests so as not to skip "readNamedType" tests.
* This should deal with some of the missing coverage... it wasn't actually running all of the happy case tests in Ion Schema Tests.
Commit: "Fixes..."
* As part of #261, I seem to have broken the `ktlintFormat` Gradle tasks. (The `ktlintCheck` tasks still work fine though.) Turns out I needed to update the `ktlint` plugin when I updated to Gradle 8. This PR updates the `ktlint` plugin, but it keeps the ktlint …

Adds readers for ordered_elements and fields constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/ConsistentDecimal.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ConsistentTimestamp.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/aliases.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ValidValuesReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/ConsistentDecimalTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/ConsistentTimestampTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ValidValuesReaderTest.kt

#256 
* Adds `ValidValuesReader` and tests
* Adds extension functions for converting from `IonValue` to `NumberRange` and `TimestampRange`.
* While working on this, I ran into problems with the `BigDecimal` and `Timestamp` both having inconsistent `compareTo` and `equals`, so I introduced `ConsistentDecimal` and `ConsistentTimestamp` as wrappers that properly implement `equals()`, `compareTo()` and `hashCode()` in a way that all three are consistent with each other.
* There is also an incidental change to `ReaderTests` that makes the test failure messages a little bit more helpful.
None
By submitting this pull request, I confirm that my contribution is made under the …

Adds reader for valid_values

---

ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampOffsetReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampPrecisionReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampOffsetReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampPrecisionReaderTest.kt

#256 
Adds readers for `timestamp_offset` and `timestamp_precision`; updates the ReaderTests accordingly.
None

Adds reader for timestamp_offset and timestamp_precision

---

ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/AnnotationsV2Reader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ContainsReader.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/AnnotationsV2ReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ContainsReaderTest.kt

#256
Adds readers for Annotations (v2) and Contains constraints. Updates `ReaderTests`.
None

Add readers for annotations and contains constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/FooterReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/HeaderReader.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/FooterReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/HeaderReaderTest.kt

#256 
* Adds readers for headers and footers, and tests.
None

Adds readers for schema headers and footers

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/TimestampPrecisionValue.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/TimestampPrecisionValueTest.kt

Fixes #270 
Changes `TimestampPrecisionValue` from an enum to a class. The class has a bunch of static constant values so that its public API is a little like an enum. This change fixes the problem with the `TimestampPrecisionRange` because we can (internally) construct a `TimestampPrecisionValue` for any timestamp to be compared against the range.
None

Fixes the way TimestampPrecisionValue is modeled

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonValueExtensions.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ReaderContext.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/util.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/Bag.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0Tests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt

#256 
- Changes the signature of `readSchema` so that it returns a `Pair<SchemaDocument, Iterator<IonValue>>`—essentially, it returns the `SchemaDocument` and any unread `IonValue`s.
- Adds some utility functions for identifying top level content (header, footer, type, open content).
- Adds implementation of `readSchema` with a lot of tests.
- Fixes a bug with the `reportError` function that showed up while testing `readSchema`. Basically, fast-fail wasn't working properly because it was only throwing on fast fail without adding the error to the ReadContext.
- Another incidental change is adding a useful `toString()` for `Bag`. I realized that the default impl was giving me things like `Bag@398c0a`, so I changed it to something …

Adds changes to read full schema document

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/Constraint.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ContinuousRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/DiscreteIntRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/NamedTypeDefinition.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/SchemaDocument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/SchemaFooter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/SchemaHeader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/aliases.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/util.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/FooterReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/HeaderReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/TypeReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/AnnotationsV2Reader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ContainsReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampOffsetReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ValidValuesReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/ContinuousRangeTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/SchemaDocumentTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0Tests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/FooterReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/HeaderReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/AnnotationsV2ReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ContainsReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/LogicConstraintsReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampOffsetReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/TimestampPrecisionReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ValidValuesReaderTest.kt

Fixes #264 
By Commit:
* [Use sets instead of lists in the ISL model](https://github.com/amazon-ion/ion-schema-kotlin/commit/364933ce5147ed58061e50fa2f5dd32d51c1bc13)
* Renames `TypeArgumentList` to `TypeArguments`
* Adds `mapToSet()` convenience function (since the kotlin standard library `map` function maps to a list).
* Changes logic constraints, contains, valid values, timestamp offset constraints to use a Set
* Changes imports in schema header to be a set.
* [Makes ContinuousRange.Limit.Unbounded an object instead of a class](https://github.com/amazon-ion/ion-schema-kotlin/commit/e3203f29eaacf8bf0f6d3092fb2fb869be0d8eb7)
* We only ever need one instance of `Unbounded`, so it makes sense for it to be an `object` instead of a …

Ease-of-use improvements for ISL model

---

.gitmodules
ion-schema/build.gradle

None
Updates to the latest commit of `ion-schema-schemas` so that we can bundle the new `commons.isl` into the Jar. While I was at it, I moved the location of the `ion-schema-schemas` submodule so that it's in the conventional "resources" location for Gradle.
amazon-ion/ion-schema-schemas#13

Moves ion-schema-schemas to resource directory and updates to latest commit

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/LogicConstraints.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/constraint/OneOfTest.kt

Fizes #278
The violation messages for matching more than 1 variant of a `one_of` constraint was incorrectly casting to `ConstraintBase` instead of `TypeInternal`. This _might_ have been fine in the past, but especially since the cyclical imports fix, there are `Type`s that do not extend `ConstraintBase`.
None.

Fix (#278) ClassCastException in OneOf implementation

---

ion-schema/src/main/kotlin/com/amazon/ionschema/util/SchemaSymbolsUtil.kt
ion-schema/src/test/java/com/amazon/ionschema/util/SchemaSymbolsUtilJavaApiTest.java
ion-schema/src/test/kotlin/com/amazon/ionschema/util/SchemaSymbolsUtilTest.kt

None.
Adds a utility that will get all of the symbols defined for types in schemas (i.e. all of the expected/possible field names, annotations, and valid values that the types define).
None.

Adds utility to get all symbol text declared in one or more schemas

---

ion-schema/src/main/kotlin/com/amazon/ionschema/IonSchemaSystemBuilder.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeImpl.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/FailFastOnInvalidAnnotationsTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

None
Allows users to configure their schema system to fail early if a value does not match the annotations constraint for a type.
This is useful for cases where people use annotations to indicate the type of a value. For example:
```
type::{
name: Address,
one_of: [
{
annotations: required::closed::[PoBox],
fields: {
addressee: string,
box_no: int,
zip: int,
}
},
{
annotations: required::closed::[StreetAddress],
fields: {
addressee: string,
street: string,
city: string,
state: string,
zip: int,
}
],
}
```
In this case, if a struct is annotated with `PoBox`, then there's not much point in checking it against the fields of the `StreetAddress` type. This has the benefit of reducing noise in the violations messages (why bother telling me …

Add optimization to fail-fast on annotations

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/Constraint.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ContinuousRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/AnnotationsV2Reader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/SchemaSymbolsUtil.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/AnnotationsV2ReaderTest.kt

None
* Updates the `AnnotationsV2` model to have special support for the simplified syntax, since it was discovered that there are significant performance improvements by doing so. (See #287) Also updates the schema reader and `SchemaSymbolUtil` accordingly.
* Fixes a typo in `ContinuousRange.toString()`
* Adds factory functions that will allow users to create a `Fields` constraint directly from `TypeArgument`s instead of requiring `VariableOccurringTypeArgument`s.
None

Minor improvements to Ion Schema Model

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/UserReservedFields.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/IonSchemaResult.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/IonSchemaWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/FooterWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/HeaderWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/TypeWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/ConstraintWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/util.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/TestUtil.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/FooterWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/HeaderWriterTest.kt

None
This is the start of a writer for the Ion Schema model. It includes interfaces for a schema writer, type writer, constraint writers, and implementations of `HeaderWriter` and `FooterWriter`.
There's also a little bugfix in `IonSchemaResult`.
None

Adds skeleton for ISL Writer

---

ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/ExponentWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/LengthConstraintsWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/PrecisionWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/ConstraintTestBase.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/ExponentWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/LengthConstraintsWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/PrecisionWriterTest.kt

None
* Adds helper function for writing `DiscreteIntRange`s
* Adds `ConstraintWriter` impl for all `*_length` constraints as well as `precision` and `exponent`.
* Adds tests for the constraint writers
None

Adds writers for range-based constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/ConsistentDecimal.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ConsistentTimestamp.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/Constraint.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ContinuousRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/DiscreteIntRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/TimestampPrecisionRange.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/ValidValue.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/aliases.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/constraints/ValidValuesReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/ranges.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/TimestampPrecisionWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/ValidValuesWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/ranges.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/model/ContinuousRangeTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/internal/constraints/ValidValuesReaderTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/TimestampPrecisionWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/ValidValuesWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/util.kt

None
I learned a lot about how awkward some of the APIs are while working on the `ValidValuesWriter`, so I ended up reworking some of the model to make it nicer to use.
The big changes are (1) making `ContinuousRange` an `open` class so that `TimestampRange`, etc. can be concrete classes rather than just an alias for `ContinuousRange<Timestamp>`, and (2) removing a level of wrapping in `ValidValues`. This resulted in some refactoring in the reader side.
There are also a number of smaller changes such as adding some factory methods to `ConsistentDecimal` and `ConsistentTimestamp`.
Finally, I did actually add a writer for `valid_values` and `timestamp_precision`, as well as unit testing of the same.
**Related PRs in ion-schema, …

Refactors ranges and adds writers for ValidValues and TimestampPrecision

---

ion-schema/src/main/kotlin/com/amazon/ionschema/model/Constraint.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/model/VariablyOccurringTypeArgument.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/TypeWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/FieldsWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/LogicConstraintsWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/OrderedElementsWriter.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/FieldsWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/LogicConstraintsWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/OrderedElementsWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/util.kt

None
* Adds writers for more constraints.
* Adds convenience constructors for constraints that accept a list of type arguments
* Adds factory methods for constructing a `VariablyOccuringTypeArgument` from a `TypeArgument`
* Moves `writeTypeArguments` from the `TypeWriter` interface to be an extension function instead.
None

Adds writers for Fields, OrderedElements, and logic constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/AnnotationsV2Writer.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/ContainsWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/ElementWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/FieldNamesWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/Ieee754FloatWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/RegexWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/constraints/TimestampOffsetWriter.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/AnnotationsV2WriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/ContainsWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/ElementWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/FieldNamesWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/Ieee754FloatWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/RegexWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/internal/constraints/TimestampOffsetWriterTest.kt

None
* Adds writers for `AnnotationsV2`, `Contains`, `Element`, `FieldNames`, `Ieee754Float`, and `Regex` constraints.
None.

Adds writers for remaining constraints

---

ion-schema/src/main/kotlin/com/amazon/ionschema/writer/IonSchemaWriter.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/IonSchemaWriterV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/TypeWriterV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/writer/internal/VersionedIonSchemaWriter.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/IonSchemaWriterTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/WriterTests.kt

None
* Changes `IonSchemaWriter` to be an `object` and the entry point to writing an Ion Schema.
* Creates an `internal` interface called `VersionedIonSchemaWriter` to replace the former `IonSchemaWriter`
* Adds  ISL 2.0 writer implementations for Types and SchemaDocuments
* Creates a test harness that uses `ion-schema-tests` with the Ion Schema writer.
None.

Adds writers for SchemaDocument and types

---

ion-schema/src/main/kotlin/com/amazon/ionschema/reader/IonSchemaReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/IonSchemaReaderV2_0.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/reader/internal/VersionedIonSchemaReader.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/SchemaSymbolsUtil.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/IonSchemaReaderV2_0Tests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/reader/ReaderTests.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/writer/WriterTests.kt

None
Updates the reader APIs so that the user doesn't have to know the schema version ahead of time. Now the specific version is an implementation detail, and the user interacts with the reader by calling `IonSchemaReader.readSchema()`.
None

Update reader APIs

---

ion-schema/src/main/kotlin/com/amazon/ionschema/Violations.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeNamed.kt

None.
I changed the implementation of `ViolationChild` so that it's not unnecessarily creating clones of `IonValue`s.
Also changed the implementation of `TypeNamed` so that it doesn't create a new struct _and_ clone the entire type definition every time it validates a value.
My informal performance testing shows a significant improvement. I created a representative schema:
```
type::{ name: A, type: int }
type::{ name: B,  type: string }
type::{ name: C, type: $any }
type::{
name: abc,
fields: {
a: A,
b: B,
c: C,
}
}
```
And tested it using a set of values that were all valid for the type `abc` and another set that were all invalid. These results were measured by running warmups until the time was stable, using an …

Remove extraneous clones in TypeNamed and ViolationChild

---

ion-schema/build.gradle
ion-schema/src/main/kotlin/com/amazon/ionschema/IonSchemaSystemBuilder.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/ConstraintFactoryDefault.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/IonSchemaSystemImpl.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Regex.kt
ion-schema/src/main/kotlin/com/amazon/ionschema/util/RegexImplementation.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/AlternateRegexImplementationTest.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/IonSchemaTestsRunner.kt

None
Adds an option to the `IonSchemaSystemBuilder` that allows users to provide an alternate regex implementation in order to e.g. get better performance characteristics.
None.

Add option to provide alternate regex implementation

---

ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0.kt
ion-schema/src/test/kotlin/com/amazon/ionschema/internal/SchemaImpl_2_0_Test.kt

Fixes #305 
Also related to #304 
There was incorrect logic for handling appending a new type to a schema in `SchemaImpl_2_0.plusType()`. The `idx == isl.lastIndex` meant that the new type would be inserted _before_ the last value, no matter what it was. So, when the existing schema had only one top-level value (in this case, the `$ion_schema_2_0` version marker), the new type would be inserted before the version marker, which is illegal.
Now, the logic for adding the type in `plusType()` is as follows:
1. If we find a type with the same name, replace it with the new type
2. If we find a schema footer, insert the new type immediately before the schema footer
3. Otherwise, append to the very end of the existing schema.
(This is what it …

Fix plusType for schema that contains only ISL 2.0 version marker
